import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd
import os

#Use to manually load latex path on IAS machines if not loaded earlier 
os.environ["PATH"] += os.pathsep + "/software/texlive/2023/bin/x86_64-linux"

#Import using pandas
df = pd.read_csv("./data/PhaseNoise_488.csv")

#Activate style
plt.style.use("./styles/presentation.mplstyle")

#Create axis (default is 1x1)
fig, ax = plt.subplots()

xmin = 1
xscale = 10**-6
xscale_suffix = 'M'

#plot on axis (column names are generated by pandas)
ax.plot((df["output noise: (USB, dBc/Hz) X"].values)*xscale ,df["output noise: (USB, dBc/Hz) Y"].values)

# ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: '{:,.2f}'.format(x*10**9) + 'n'))

#Set axis labels
ax.set_xlabel(r"Frequency Offset [\si{%s\hertz}]" % (xscale_suffix))
ax.set_ylabel(r"Phase noise [\si{\decibel c/\hertz}]")

#Show legend
plt.legend(loc='upper center', ncol=2, bbox_to_anchor=(0.5, 1.15))

plt.savefig("./plots/pn_488.svg")
plt.show()
